### ISSUE TITLE
ContentType template not running

### ISSUE THREAD

**Issue by MathieuLoutre** [static-dev/spike-contentful#74]
Hi there!

Just playing with Spike and I like the cleanliness so far. I'm trying to get a basic blog setup through contentful and I'm trying the `template` option configured like so:

```js
new Contentful({
      addDataTo: locals,
      accessToken: 'xxxxx',
      spaceId: 'xxxxx',
      contentTypes: [
        {
          name: 'podcasts',
          id: 'podcast',
          filters: {
            order: 'fields.number'
          },
          template: {
            path: 'views/_podcast.html',
            output: (podcast) => `podcasts/${podcast.number}-${slug(podcast.guestName)}.html`
          }
        },
        {
          name: 'notes',
          id: 'notes'
        }
      ]
    })
```

I have a basic template using `item` as a variable in `views/_podcast.html` (same directory as my index) but the `output` function never runs.

I dig a little bit of digging and it keeps hitting https://github.com/static-dev/spike-contentful/blob/master/lib/index.js#L53 instead of going ahead.

`templatePairs` is correct (= `{ 'views/_podcast.html': 0 }`) but `p` is pointing to the `index.html` (my only template) so it never runs the past L53. If I don't ignore my `_podcast.html` template it causes an error because `item`, if I ignore it `ctx.resourcePath` never points to the `_podcast.html` template and therefore never goes further.

Am I doing something wrong or is this broken?

**Comment by jescalan** [comment]
Yep, so your template file is ignored since it has an underscore prefix, which is why it isn't compiling. The [docs have been adjusted](https://github.com/static-dev/spike-contentful#templates) to account for this case, and it's mentioned in [the release notes](https://github.com/static-dev/spike-contentful/releases/tag/v2.0.0) for the latest major version. Despite that I know it's easy to miss, as the latest release was a major breaking change, so I'm sorry about that!

If you remove the underscore from your template name it should work again. Thanks so much for the clear issue and for really digging and investigating 😁

**Comment by MathieuLoutre** [comment]
Hi there! Sorry, I must be confused. The docs say 

`Note: you also will need to prevent Spike from attempting to render your template file normally by adding your templates to Spike's ignore option, or adding an underscore to the file name.`

and the release notes say

`If you are upgrading from a previous version, you must also ensure that the single page templates are not prefixed by an underscore or ignored.`

Also, I have tried to remove the underscore to get the file to be picked up, but it tries to render with `item` which doesn't exist for a standalone page (or at least that's my understanding of the error)

**Comment by MathieuLoutre** [comment]
This is the error I get on Node v8.2.1:
```
{ ModuleBuildError: Module build failed: TypeError: Cannot read property 'fields' of undefined
    at eval (eval at module.exports (/Users/Otter/Programming/spike-test/node_modules/reshape-code-gen/lib/scoped_eval.js:9:10), <anonymous>:1:155)
    at eval (eval at module.exports (/Users/Otter/Programming/spike-test/node_modules/reshape-code-gen/lib/scoped_eval.js:9:10), <anonymous>:1:200)
    at evalNode (/Users/Otter/Programming/spike-test/node_modules/reshape-eval-code/lib/index.js:27:72)
    at node.attrs.(anonymous function).node.attrs.(anonymous function).map (/Users/Otter/Programming/spike-test/node_modules/reshape-eval-code/lib/index.js:16:20)
    at Array.map (native)
    at util.modifyNodes (/Users/Otter/Programming/spike-test/node_modules/reshape-eval-code/lib/index.js:14:41)
    at when.resolve.then (/Users/Otter/Programming/spike-test/node_modules/reshape-plugin-util/lib/index.js:26:29)
    at tryCatchReject (/Users/Otter/Programming/spike-test/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/Otter/Programming/spike-test/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/Users/Otter/Programming/spike-test/node_modules/when/lib/makePromise.js:592:4)
    at ContinuationTask.run (/Users/Otter/Programming/spike-test/node_modules/when/lib/makePromise.js:702:24)
    at runLoaders (/Users/Otter/Programming/spike-test/node_modules/webpack/lib/NormalModule.js:194:19)
    at /Users/Otter/Programming/spike-test/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /Users/Otter/Programming/spike-test/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/Users/Otter/Programming/spike-test/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at tryCatchReject (/Users/Otter/Programming/spike-test/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/Otter/Programming/spike-test/node_modules/when/lib/makePromise.js:804:4)
    at Rejected.when (/Users/Otter/Programming/spike-test/node_modules/when/lib/makePromise.js:625:4)
    at Pending.run (/Users/Otter/Programming/spike-test/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/Otter/Programming/spike-test/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/Otter/Programming/spike-test/node_modules/when/lib/Scheduler.js:27:9) id: '60d077ca' }
```
If I remove all variables (`item.whatever`) from the podcast template, the error disappears and it gets rendered as a standalone page and not once for each item as expected.

**Comment by jescalan** [comment]
Ah nice catch on the docs, I must have missed that little section in the upgrade process. I'll change it now!

Hmm, do you have a public copy of the project anywhere? If not, could you privately share a copy of it with me so I can take a look? I am unable to reproduce this locally, or [in a test](https://github.com/static-dev/spike-contentful/blob/master/test/fixtures/template/template.html). Sorry for the issues and hopefully we can get them resolved soon!

**Comment by MathieuLoutre** [comment]
That's ok, all part of the fun of tinkering! I'll put a test case together for you before tomorrow.

**Comment by jescalan** [comment]
Thank you @MathieuLoutre, looking forward to it 😁

**Comment by MathieuLoutre** [comment]
Hi @jescalan, I've put together the smallest test I could muster (and still reproduces): https://github.com/MathieuLoutre/spike-contentful-test

Must be something silly at this point if it works on your end. Anyway, thanks for looking into this.

Steps to reproduce: `npm install && spike compile`

I created a new project with `spike new test-project` and chose no sugar, then added the sugar again for CSS manually. The rest should be pretty standard I think. Let me know if you need anything else from me!

**Comment by MathieuLoutre** [comment]
Any luck with that @jescalan?

**Comment by MathieuLoutre** [comment]
Not sure what's going on exactly, but using the latest version from master seems to have fixed the problem. Can't pinpoint it though...

**Comment by jescalan** [comment]
Ah great! It might have been just updating dependencies. Either way, glad this was resolved, and sorry I was so slow getting back to this, have been busy :(
